### ISSUE TITLE
Latest update - Syntax error in prowl.py

### ISSUE THREAD

**Issue by TeRmInAlCrAzY** [itsmegb/LazyLibrarian#75]
Hi,

Just did an update to latest.

```
E:\LazyLibrarian>git pull
From https://github.com/DobyTang/LazyLibrarian
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.3.0      -> 1.3.0
Already up-to-date.
```

When I try to run LazyLibrarian, I get

```
E:\LazyLibrarian>python LazyLibrarian.py
Traceback (most recent call last):
  File "LazyLibrarian.py", line 13, in <module>
    import lazylibrarian
  File "E:\LazyLibrarian\lazylibrarian\__init__.py", line 30, in <module>
    from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
  File "E:\LazyLibrarian\lazylibrarian\postprocess.py", line 35, in <module>
    from lazylibrarian.notifiers import notify_download, custom_notify_download
  File "E:\LazyLibrarian\lazylibrarian\notifiers\__init__.py", line 22, in <module>
    import prowl
  File "E:\LazyLibrarian\lazylibrarian\notifiers\prowl.py", line 51
    response = http_handler.getresponse()
           ^
SyntaxError: invalid syntax
```

**Comment by noisyparker** [comment]
I ran into this, as well.

I had thought it might be an indentation problem, and when I indented these lines:
>     51	        response = http_handler.getresponse()
>     52	        request_status = response.status
>     53	        
>     54	        if request_status == 200:
>     55	                logger.info(' Prowl notifications sent.')
>     56	                return True
>     57	        elif request_status == 401:
>     58	                logger.info(' Prowl auth failed: %s' % response.reason)
>     59	                return False
>     60	        else:
>     61	                logger.info(' Prowl notification failed.')
>     62	                return False

...it did indeed go on, only to hit another error:
> Traceback (most recent call last):
>   File "/opt/lazylibrarian/LazyLibrarian.py", line 13, in <module>
>     import lazylibrarian
>   File "/opt/lazylibrarian/lazylibrarian/__init__.py", line 30, in <module>
>     from lazylibrarian import logger, postprocess, searchbook, searchrss, librarysync, versioncheck, database, \
>   File "/opt/lazylibrarian/lazylibrarian/postprocess.py", line 35, in <module>
>     from lazylibrarian.notifiers import notify_download, custom_notify_download
>   File "/opt/lazylibrarian/lazylibrarian/notifiers/__init__.py", line 37, in <module>
>     prowl_notifier = prowl.Prowl_Notifier()
> AttributeError: 'module' object has no attribute 'Prowl_Notifier'

True enough, the class is actually ProwlNotifier. When I removed the _ in the `__init__.py` reference, it was able to start. If there are other issues beyond that, they aren't obvious to me yet.

**Comment by TeRmInAlCrAzY** [comment]
Looks like it has now been fixed - closing.
